### ISSUE TITLE
Removal Candidate

### ISSUE THREAD

**Issue by Adurol** [KaOS-Community-Packages/dfilemanager#1]
This Package will be removed in 7 days from KCP.

Reason: **[Blind copy](https://aur.archlinux.org/packages/dfilemanager-git/)**

Please see also: [Using KaOS Community Packages](https://kaosx.us/phpBB3/viewtopic.php?f=12&t=145) and [KCP Guide](https://kaosx.us/kcp-guide/)

**Comment by forostm** [comment]
I followed the instructions to compile in the [official docs.](http://dfilemanager.sourceforge.net/Docs)

The pkgver () was copied in [VCS package guidelines](https://wiki.archlinux.org/index.php/VCS_package_guidelines)

I accept your decision, if you consider appropriate remove it. :)

**Comment by demmm** [comment]
Since this app does not have any releases yet, why not make this a reproducible build?  Use a SF generated tar, then there is no confusion about any copy, if there ever is an issue, much easier to point back to a checkout tar that did not have an issue.
This actually would be following KaOS guidelines instead of using what another distro does......
Examples:
https://github.com/KaOSx/apps/commit/caa7de10dc599efd00522585f6df105e685e1465
https://github.com/KaOSx/apps/blob/master/inxi/PKGBUILD

The link to a tar for this app would be:
https://sourceforge.net/code-snapshots/git/d/df/dfilemanager/code.git/dfilemanager-code-6cd4f58b1940dd7e7baf65a1bb9a5dac487ff4c5.zip

And instead of following Arch (rather new) way of using complete incomprehensive version numbers, why not set this to 0.1?  And use x.x.70 for alpha software, x.x.80 for beta and x.x.90 for RC? Or the common way of just a date?
None of the packages in KaOS repos will ever follow this convoluted versioning.

**Comment by forostm** [comment]
@demmm I will rebuild the PKGBUILD following your suggestions for the version number.
